# Generated by Django 5.0.3 on 2024-04-04 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expensecategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='category',
            new_name='category_name',
        ),
    ]
