# Generated by Django 5.0.3 on 2024-04-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_category_expensecategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expensecategory',
            old_name='category_name',
            new_name='category',
        ),
    ]
