# Generated by Django 5.0.3 on 2024-04-04 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_rename_category_name_expensecategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='month_year',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
