# Generated by Django 5.0.3 on 2024-04-04 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_expensecategory_month_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('cat_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('month_year', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='cat_expense',
        ),
        migrations.RemoveField(
            model_name='expensecategory',
            name='month_year',
        ),
    ]
