# Generated by Django 5.0.3 on 2024-04-07 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_expensedetails_remove_expensecategory_cat_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='fixed_expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expensedetails',
            name='month_year',
            field=models.DateField(default=datetime.date(2024, 4, 1)),
        ),
    ]
