# Generated by Django 5.0.3 on 2024-04-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_expensesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensesummary',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
