# Generated by Django 5.0.3 on 2024-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_expensesummary_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='emergency',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
