# Generated by Django 5.0.3 on 2024-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_income_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
