# Generated by Django 5.0.3 on 2024-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_rename_event_devent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('expense', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tcat',
            name='status',
        ),
    ]
