# Generated by Django 5.0.3 on 2024-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0018_catevent_remove_tcat_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devent',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='catevent',
            name='expense',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
