# Generated by Django 5.0.3 on 2024-04-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_devent_collected_devent_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
