# Generated by Django 3.2.12 on 2024-07-10 18:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_income_savings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensedetails',
            name='month_year',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
        migrations.AlterField(
            model_name='expensesummary',
            name='month_year',
            field=models.DateField(default=datetime.date(2024, 7, 1)),
        ),
    ]
